export { default as LoginView } from './LoginView'
export { default as SignUpView } from './SignUpView'
export { default as ForgotPassword } from './ForgotPassword'
export { default as ConfirmCode } from './ConfirmCode'
export { default as CookiesMng } from './CookiesMng'
