/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://yu6e6ifx05.execute-api.us-east-1.amazonaws.com/master",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://ycwf22ysgvajraiqzytejw7i4y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-iqhrbg5g7ffejlk3bdzllnvnbq",
    "aws_cognito_identity_pool_id": "us-east-1:81b9cb1c-fa71-40b3-bf77-040d26125566",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_lIDoLvjDT",
    "aws_user_pools_web_client_id": "435iuvadsg747nbjvcladi22do",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL",
        "PHONE_NUMBER"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OPTIONAL",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": "6",
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "appsls35b3bdc71fa2449bb5d2de82371b2eaf84656-master",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
